config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations',  :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get '/register' => 'devise/registrations#new'
    get '/settings' => 'devise/registrations#edit'
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

  end

  root 'static_pages#home'

  resources :posts, only: [:create, :update, :delete, :edit, :update]
  resources :users, only: [:show, :index] do
    resources :posts, except: [:index, :create, :delete]
  end

  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  get 'friend_requests', to: 'friendships#friend_requests', as: 'friend_requests'
  post 'friend_requests', to: 'friendships#confirm_request', as: 'confirm_request'
  get '/friends', to: 'friendships#index', as: 'friends'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :posts, dependent: :destroy, inverse_of: :user
  has_many :likes, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy, inverse_of: :user
  has_many :post_likes, -> { where :likeable_type => 'Post' }, class_name: 'Like'
  has_many :comment_likes, -> { where :likeable_type => 'Comment' }, class_name: 'Like'

  has_many :friend_requests, -> {where :request_status => 'pending'}, foreign_key: :friend_id, class_name: 'Friendship'
  has_many :friend_request_users, through: :friend_requests, source: :user

  has_many :requested_friends, -> {where :request_status => 'pending'}, foreign_key: :user_id, class_name: 'Friendship'
  has_many :requested_friend_users, through: :requested_friends, source: :friend

  has_many :requested_friendships, -> {where :request_status => 'confirmed'}, class_name: 'Friendship'
  has_many :confirmed_friendships, -> {where :request_status => 'confirmed'}, class_name: 'Friendship', foreign_key: :friend_id
  
  has_one :bio, dependent: :destroy
  accepts_nested_attributes_for :bio
  validates :name, presence: true
  has_attached_file :profile_picture, 
                      styles: {:medium => "300x300#", :thumb => "55x55#", },
                      :default_url => 'http://facebook-clone-sample-app.s3.amazonaws.com/users/profile_pictures/000/000/001/:style/missing.gif'
  validates_attachment :profile_picture, content_type:  { content_type: /\Aimage\/.*\Z/ },
                                           size: { in: 0..1.megabytes }


  

  def friends
    user_ids = self.requested_friendships.collect {|f| f.friend_id}
    user_ids.concat self.confirmed_friendships.collect {|f| f.user_id}
    User.where(id: user_ids)
  end

  def find_friendship(friend_id)
    friendship = Friendship.where("(user_id = ? AND friend_id = ?) OR (friend_id = ? AND user_id = ?)", self.id, friend_id, self.id, friend_id).take
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      puts auth
      user.provider = auth.provider
      user.uid = auth.uid

      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.skip_confirmation!
  #   user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	def show
		@user = User.find_by(id: params[:id])
	    redirect_to root_url and return unless @user.confirmed_at

	end
	def index
	    @users = User.where.not(:confirmed_at => nil).paginate(page: params[:page])
	end
	private


end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class:"gravatar")
	end	
	
    def friendship_status(user)
	   if current_user.friends.include?(user)
	   		:friend
	   elsif current_user.friend_request_users.include?(user) 
	   		:awaiting
	   elsif current_user.requested_friend_users.include?(user)
	   		:requested 
	   elsif current_user == user
	   		:self
	   else
	   		:not_friend
	   end     	
    end

   	def check_if_friends
		friend = User.find_by(id: params[:user_id])
		relationship = friendship_status(friend)
		if relationship != :friend and relationship != :self
			redirect_to root_path			
		end				
	end

end

app/views/users/index.html.erb
<%= will_paginate %>
	<% @users.each do |user| %>
		<div class="user row well" >
			<h4><%= link_to(user.name, user_path(user)) %></h4> 
			<% status = friendship_status(user) %>
			<% if status == :not_friend %> 
				<%= render 'users/shared/friend_request', user: user %>
			<% elsif status == :awaiting%>
				<div class="awaiting">
					<p>
						<%= render 'layouts/confirm_request', friendship: current_user.find_friendship(user) %>
						<%= render 'layouts/decline_request', friendship: current_user.find_friendship(user) %>	
					</p>
				</div>
			<% elsif status == :requested%>
				<div class="requested">
					<p class="text-muted">Friend Request Sent</p>
				</div>
			<% elsif status == :friend%>
				<div class="friends">
					<p class="text-info">Currently Friends</p>
				</div>
			<% end %>
		</div>	
	<%end %>
<%= will_paginate %>

app/views/users/show.html.erb
<div class="row user-profile">
	<div class="profile-picture col-md-4"><h2><%= image_tag @user.profile_picture.url(:medium), class: "img-responsive thumbnail" %></h2></div>
	<div class="user-info col-md-8">
		<h2 class="user-name"><%= @user.name %></h2>
		<% status = friendship_status(@user) %>
		<% if status == :not_friend %> 
			<%= render 'users/shared/friend_request', user: @user %>
		<% elsif status == :awaiting%>
			<div class="awaiting">
				<p>
					<%= render 'layouts/confirm_request', friendship: current_user.find_friendship(@user) %>
					<%= render 'layouts/decline_request', friendship: current_user.find_friendship(@user) %>	
				</p>
			</div>
		<% elsif status == :requested%>
			<div class="requested">
				<p >Friend Request Sent</p>
			</div>
		<% elsif status == :friend%>
					<%= render 'layouts/defriend', friend: @user,  friendship: @user.find_friendship(current_user.id) %>

		<% elsif status == :self%>
			<%= link_to "Edit Profile", settings_path %>
		<% end %>

		<% if !@user.bio.nil? && !@user.bio.description.nil?%>
			<div class="user-bio well row">
				<h5>About <%= @user.name %>:</h5>
				<p><%= @user.bio.description %></p>
			</div>
		<%end%>
	</div>
</div>
<hr>
<%if !@user.posts.empty? and (friendship_status(@user) == :self or friendship_status(@user) == :friend)%>
<div class="row user-posts">
	<h3><%= @user.name %>'s Posts</h3>
	<% @user.posts.each do |post| %>
		<%= render 'layouts/timeline_post', post: post %>
	<% end %>
	
</div>	
<% end %>