config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations',  :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get '/register' => 'devise/registrations#new'
    get '/settings' => 'devise/registrations#edit'
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

  end

  root 'static_pages#home'

  resources :posts, only: [:create, :update, :delete, :edit, :update]
  resources :users, only: [:show, :index] do
    resources :posts, except: [:index, :create, :delete]
  end

  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  get 'friend_requests', to: 'friendships#friend_requests', as: 'friend_requests'
  post 'friend_requests', to: 'friendships#confirm_request', as: 'confirm_request'
  get '/friends', to: 'friendships#index', as: 'friends'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :body, presence: true
	validates :user_id, presence: true
	belongs_to :user, inverse_of: :posts
	has_many :likes, as: :likeable, dependent: :destroy 
	has_many :comments, dependent: :destroy 

	has_attached_file :picture, 
	                  styles: {:large => "800x800>",:medium => "500x500>", :thumb => "200x200>"}
	validates_attachment :picture, content_type:  { content_type: /\Aimage\/.*\Z/ },
													size: { in: 0..1.megabytes }


												

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_if_friends, only: [:show]

	def show
		@post = Post.find_by(id: params[:id])
		@user = @post.user
		@comment = Comment.new(user_id: current_user.id, post_id: @post.id)

	end

	def new
		@user = current_user
		@post = @user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to user_post_path(@post.user, @post)

		else
			flash[:warning] = "Please correct errors."
			render 'new'
		end
	end

	def edit
		@post = Post.find_by(:id => params[:id])
	end

	def update
		@post = Post.find_by(:id => params[:id])
		if @post.update_attributes(post_params)
			flash[:success] = "Post successfully updated!"
			redirect_to user_post_path(@post.user, @post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find_by(id: params[:id])
		@post.destroy
		redirect_to root_path
		
	end

	private

	def post_params
		params.require(:post).permit(:body, :user_id, :picture)
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="form-vertical">
	<div class="col-md-8 col-md-offset-2">
	<h1>Edit your post:</h1>
	<%= form_for(@post) do |f| %>
		<div class="form-group row" >
			<%= f.label :body, class: "control-label" %>
			<%= f.text_area :body, class: "form-control", placeholder: "Tell us what you are thinking.." %>
		</div>
		<div class="form-group row">
		    <%= f.label :picture, class: "control-label" %>
		    <%= f.file_field :picture, class: "form-control" %>
	    </div>
	    <div class="form-group row">
			<%= f.submit "Save Changes", class:"btn btn-primary"%>
		</div>
	<% end %>
	</div>
</div>	

app/views/posts/new.html.erb
<div class="form-vertical">
	<div class="col-md-8 col-md-offset-2">
	<h1>Create Post:</h1>
	<%= form_for(@post) do |f| %>
		<div class="form-group row" >
			<%= f.label :body, class: "control-label" %>
			<%= f.text_area :body, class: "form-control", placeholder: "Tell us what you are thinking.." %>
		</div>
		<div class="form-group row">
		    <%= f.label :picture, class: "control-label" %>
		    <%= f.file_field :picture, class: "form-control" %>
	    </div>
	    <div class="form-group row">
			<%= f.submit "Create Post", class:"btn btn-primary"%>
		</div>
	<% end %>
	</div>
</div>	

app/views/posts/show.html.erb
<div class="row timeline-post panel panel-default">

	<div class="col-sm-12 panel-heading">
		<%if @user == current_user %>
			<div class="pull-right">
			<span class="btn btn-group btn-group-sm">
				<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-info" %>
				<%= link_to "Delete Post", user_post_path(@user, @post), class: "btn btn-danger", data: { confirm: "Are you sure?" }, method: :delete %>
			</span>
			</div>

		<% end %>

		<span class="profile-picture pull-left"><%= image_tag @post.user.profile_picture.url(:thumb), class: "img-responsive thumbnail" %></span>
		<h4><%= link_to(@post.user.name.humanize, user_path(@post.user)) %></h4>
		<p class="text-muted"><%= time_ago_in_words(@post.created_at) %> ago</p>


	</div>

	<div class="post-body panel-body">
		<%= @post.body %>
		<% if @post.picture_file_name %>
			<%= image_tag(@post.picture.url(:thumb), class: "img-responsive")%>
		<% end %>

	</div>
	<div class="post-body panel-footer">

		<div class="likes">	
		 	<%= render 'layouts/likes', object: @post %>
		</div>
		<hr class="hr-thin">
		<div class="comments">
			<% @post.comments.each do |comment| %>
				<div class="comment">
					<div class="col-sm-12">
						<div class="profile-picture pull-left"><%= image_tag comment.user.profile_picture.url(:thumb), class: "img-responsive thumbnail" %></div>
						<h4><%= link_to(comment.user.name.humanize, user_path(comment.user)) %></h4>
						<p class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago</p>

					</div>
					<p class="comment body"><%= comment.body%></p>
					<% if comment.user == current_user %>
						<%= link_to "Edit Comment", edit_comment_path(comment) %>
						 | 
						<%= link_to "Delete Comment", comment_path(comment), method: :delete %>
					<% end %>
					<div class="comment likes">
						<%= render 'layouts/likes', object: comment%>
					</div>
				</div>
			<% end %>
			<div class="new-comment">
				<%= form_for @comment do |f|%>
					<h5>Post a new comment:</h5>
					<%= f.text_area :body, class: "form-control", placeholder: "Leonard likes this"%>
					<br>
		   			<%= f.hidden_field :post_id %>
					<%= f.hidden_field :user_id %>
					<%= f.submit "Post Comment", class: "btn"%>
				<% end %>
			</div>
		</div>
	</div>
</div>