config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations',  :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get '/register' => 'devise/registrations#new'
    get '/settings' => 'devise/registrations#edit'
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

  end

  root 'static_pages#home'

  resources :posts, only: [:create, :update, :delete, :edit, :update]
  resources :users, only: [:show, :index] do
    resources :posts, except: [:index, :create, :delete]
  end

  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  get 'friend_requests', to: 'friendships#friend_requests', as: 'friend_requests'
  post 'friend_requests', to: 'friendships#confirm_request', as: 'confirm_request'
  get '/friends', to: 'friendships#index', as: 'friends'

end

app/views/layouts/_confirm_request.html.erb
<div class="confirm-request form-group">
	<%= button_to "Confirm Friendship", confirm_request_path, params: {id: friendship.id}, class: "btn btn-success" %>
</div>

app/views/layouts/_decline_request.html.erb
<div class="decline-request form-group">
	<%= button_to "Decline", friendship_path(friendship), method: :delete, class: "btn btn-danger" %>
</div>

app/views/layouts/_defriend.html.erb
<div class="defriend">
	<%= button_to "Defriend", friendship_path(friendship), class: "btn btn-danger",method: :delete, data: {confirm: "Defriend #{friend.name}?"} %>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container footer-info">
		<small>A project in Ruby on Rails to replicate the basic functionality of Facebook.</small>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="container">
	<div id="menu" class="navbar navbar-default navbar-fixed-top">

         <div class="navbar-header">
          <button class="btn btn-success navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="glyphicon glyphicon-chevron-down"></span>

          </button>
          <div id="logo">
          		<p id="logo-intro">This is totally</p>
        		<%= link_to "Facebook", root_path, id: "home"%>
        	</div>
        </div>	
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

			<% if user_signed_in? %>
				<li class="nav <%= include_active(root_path) %>"><%= link_to "Home", root_path %></li>
				<li class="nav <%= include_active(friends_path) %>"><%= link_to "Friends", friends_path %></li>
 				<li class="nav <%= include_active(friend_requests_path) %>">
 				<%= link_to "Friend Requests 
 				#{!current_user.friend_requests.empty? ? '(' + current_user.friend_requests.length.to_s + ')' : ''}", friend_requests_path%></li>
				<li class="nav <%= include_active(users_path) %>"><%= link_to "Possble Friends", users_path %></li>
				<li class="nav <%= include_active(new_user_post_path(current_user)) %>"><%= link_to "Create Post", new_user_post_path(current_user) %></li>	 				
				<li class="nav <%= include_active(user_path(current_user)) %>"><%= link_to "Profile", user_path(current_user)%></li>
				<li class="nav"><%= link_to "Logout", logout_path%></li>
			<% else %>
				<li class="nav <%= include_active(login_path) %>"><%= link_to "Login", login_path %></li>
				<li class="nav <%= include_active(new_user_registration_path) %>"><%= link_to "Register", new_user_registration_path %></li>
			<% end %>
		</ul>
		</div>
	</div>
</header>

app/views/layouts/_likes.html.erb
<% if object.likes.count > 0 %>
	<%
		names = object.likes.collect {|like| like.user.name}
		likers = names.join("<br>")
	%>
	<span class="likes-summary" data-html="true" data-toggle="tooltip" data-placement="left" title="<%= likers.to_s %>"><%= "#{ pluralize(object.likes.count, "Like")}" %></span>
<% else %>
	<%= "#{ pluralize(object.likes.count, "Like")}" %>
<% end %>
<% like = object.likes.find { |like| like.user == current_user }%>
<%if like %>	
	<%= link_to(raw(" <span class= 'glyphicon glyphicon-thumbs-down'></span> Unlike"), like_path(like), method: :delete )%>
<% else %>
<%= link_to(raw(" <span class= 'glyphicon glyphicon-thumbs-up'></span> Like"), {controller: "likes", action: "create", 
	like: {user_id: current_user, likeable_id: object, likeable_type: object.class.to_s}}, method: :post)%>
<% end %>

app/views/layouts/_post.html.erb
<hr>
<%= post.body %>
<% if post.picture_file_name %>
	<%= image_tag(post.picture.url(:thumb))%>
<% end %>
<p><%= link_to("View Post", user_post_path(post.user, post)) %></p>

app/views/layouts/_timeline_post.html.erb
<div class="row timeline-post panel panel-default">

<div class="col-sm-12 panel-heading">
		<span class="profile-picture pull-left"><%= image_tag post.user.profile_picture.url(:thumb), class: "img-responsive thumbnail" %></span>
		<h4 class=""><%= link_to(post.user.name.humanize, user_path(post.user)) %></h4>
		<p class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</p>
</div>
	<div class="post-body panel-body">
		<%= post.body %>
		<% if post.picture_file_name %>
			<%= image_tag(post.picture.url(:thumb), class: "img-responsive")%>
		<% end %>

	</div>
	<div class="post-body panel-footer">

	 	<%= render 'layouts/likes', object: post %>
	 	<div class="comments-info">
			<%= pluralize(post.comments.count, "Comment")%>
			<%= link_to "Comment", user_post_path(post.user, post) %>
		</div>
		<p class="view-post">
			<%= link_to "View Post", user_post_path(post.user, post) %>
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).empty? ? "Facebook Clone" : (yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>">
        <a href="#" data-dismiss="alert" class="close">&times;</a>

			<%= message %>
		</div>
	<% end %>
	<div class="container">
		<div class="col-md-10 col-md-offset-1">
			<%= yield %>
		</div>
	</div>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>


</body>
</html>